In [38]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import matplotlib.pyplot as plt
import os
import re
import shutil
import string
import tensorflow as tf

import tensorflow_hub as hub

from tensorflow.keras import layers
from tensorflow.keras import losses
from tensorflow.keras import regularizers

from collections import Counter


import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [39]:
train_data= pd.read_csv("train_data1.csv")
train_data.dropna(axis = 0, how ='any',inplace=True)
train_data['Num_words_text'] = train_data['message'].apply(lambda x:len(str(x).split())) 
mask = train_data['Num_words_text'] >1
train_data = train_data[mask]
print(train_data)

       class                                            message  \
0   phishing  From acteamco@server2.aking.com.my  Sat Jan 24...   
1   phishing  From rm@transservis.az  Wed Jan 21 03:30:32 20...   
2   phishing  From MAILER-DAEMON Thu Sep 28 09:57:25 2017\n\...   
3   phishing  From m2266@cscv.qc.ca  Fri Feb 6 08:48:37 2015...   
4   phishing  From roberta@analiselaboratorios.com.br  Mon M...   
..       ...                                                ...   
75       ham  Subject: re : misc . questions\n\n- - - - - - ...   
76       ham  Subject: 2 nd rev dec . 1999 josey ranch nom\n...   
77       ham  Subject: re : best guess right now . . . . sho...   
78       ham  Subject: re : purge of old contract _ event _ ...   
79       ham  Subject: kerr mcgee : tomcat\n\nhey joe ,\n\nh...   

    Num_words_text  
0             1155  
1              647  
2              967  
3              582  
4             1252  
..             ...  
75            1141  
76             218  
77    

In [46]:
X_train, X_valid, y_train, y_valid =train_test_split(train_data['message'].tolist(),
                                                     train_data['class'].tolist(),
                                                     test_size=0.1,
                                                     stratify = train_data['class'].tolist(),
                                                     random_state=1)

print('Train data len:'+str(len(X_train)))
print(type(X_train))
print('Class distribution: '+str(Counter(y_train)))
print('Test data len:'+str(len(X_valid)))
print('Class distribution: '+ str(Counter(y_valid)))

Train data len:72
<class 'list'>
Class distribution: Counter({'phishing': 36, 'ham': 36})
Test data len:8
Class distribution: Counter({'phishing': 4, 'ham': 4})


In [50]:

X_train=np.asarray(X_train)

X_valid = np.array(X_valid)



C:\Users\HP\.conda\envs\tensorflow\lib\site-packages\numpy\core\_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


In [51]:
tokenizer = Tokenizer(num_words=50000)
tokenizer.fit_on_texts(X_train)
X_train = tokenizer.texts_to_sequences(X_train)
X_test  = tokenizer.texts_to_sequences(y_train)
vocab_size = len(tokenizer.word_index) + 1


AttributeError: 'int' object has no attribute 'lower'

In [ ]:
word_index = tokenizer.word_index
train_sequences = tokenizer.texts_to_sequences(train_data)
maxlen = max([len(x) for x in train_sequences])
train_padded = pad_sequences(train_sequences, padding='post', truncating='post', maxlen=maxlen)


In [52]:
print("Word index:\n", word_index)
print("\nTraining sequences:\n", train_sequences)
print("\nPadded training sequences:\n", train_padded)
print("\nPadded training shape:", train_padded.shape)
print("Training sequences data type:", type(train_sequences))
print("Padded Training sequences data type:", type(train_padded))

Word index:
 {'class': 1, 'message': 2, 'num': 3, 'words': 4, 'text': 5}

Training sequences:
 [[1], [2], [3, 4, 5]]

Padded training sequences:
 [[1 0 0]
 [2 0 0]
 [3 4 5]]

Padded training shape: (3, 3)
Training sequences data type: <class 'list'>
Padded Training sequences data type: <class 'numpy.ndarray'>
